version: '3'
services:
  rabbitmq:
    container_name: news-board-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    restart: always

  mysql:
    container_name: news-board-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    container_name: news-board-redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

  gateway:
    container_name: news-board-service-gateway
    image: news-board-gateway
    volumes:
      - ./services/gateway:/app
    depends_on:
      - rabbitmq
      - mysql
      - redis
    ports:
      - "80:8000"
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - REDIS_HOST=redis

  file:
    container_name: news-board-service-file
    image: news-board-file
    volumes:
      - ./files:/files
      - ./services/file:/app
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql

  news:
    container_name: news-board-service-news
    image: news-board-news
    volumes:
      - ./services/news:/app
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql

  user:
    container_name: news-board-service-user
    image: news-board-user
    volumes:
      - ./services/news:/app
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
