version: '3'
services:
  rabbitmq:
    container_name: news-board-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    restart: always

  mysql:
    container_name: news-board-mysql
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    volumes:
        - ./sql/init.sql:/data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mysql-cron:
    container_name: news-board-mysql-cron
    image: news-board-mysql-cron
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./sql/backups:/backups
    environment:
      - DB_HOST=mysql
      - DB_PASS=root
      - DB_NAME=dpt_news_board

  redis:
    container_name: news-board-redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

  gateway:
    container_name: news-board-service-gateway
    image: news-board-gateway
    depends_on:
      - rabbitmq
      - redis
      - file
      - user
      - news
    ports:
      - "80:8000"
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis

  file:
    container_name: news-board-service-file
    image: news-board-file
    volumes:
      - ./files:/files
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=root
      - DB_NAME=dpt_news_board

  news:
    container_name: news-board-service-news
    image: news-board-news
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=root
      - DB_NAME=dpt_news_board

  user:
    container_name: news-board-service-user
    image: news-board-user
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=root
      - DB_NAME=dpt_news_board
